export default {
  GET_SHIFTS_SAGA: "GET_SHIFTS_SAGA",
  GETTING_SHIFTS: "GETTING_SHIFTS",
  GOT_SHIFTS: "GOT_SHIFTS",
  FAILED_GETTING_SHIFTS: "FAILED_GETTING_SHIFTS",

  BOOK_SHIFT_SAGA: "BOOK_SHIFT_SAGA",
  BOOKING_SHIFT: "BOOKING_SHIFT",
  BOOKED_SHIFT: "BOOKED_SHIFT",
  FAILED_BOOKING_SHIFT: "FAILED_BOOKING_SHIFT",

  CANCEL_SHIFT_SAGA: "CANCEL_SHIFT_SAGA",
  CANCELING_SHIFT: "CANCELING_SHIFT",
  CANCELED_SHIFT: "CANCELED_SHIFT",
  FAILED_CANCELING_SHIFT: "FAILED_CANCELING_SHIFT"
};
